name: Engine Build Test
on: [ push, pull_request ]
env:
  PREMAKE_DOWNLOAD_URL: https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip
  PREMAKE_ZIP_FILE: premake.zip
  BUILD_DIRECTORY: .\Build
jobs:
  build_windows:
    name: Build Engine on Windows
    runs-on: windows-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Premake
        run: Invoke-WebRequest -Uri ${{ env.PREMAKE_DOWNLOAD_URL }} -OutFile ${{ env.PREMAKE_ZIP_FILE }}
        shell: powershell

      - name: Extract Premake
        run: Expand-Archive -Path ${{ env.PREMAKE_ZIP_FILE }} -DestinationPath ./premake
        shell: powershell
      
      - name: Generate Makefiles
        run: .\premake\premake5.exe gmake
        shell: cmd

      - name: Build Engine (Debug)
        run: make -C ${{ env.BUILD_DIRECTORY }} config=debug
        shell: cmd

      - name: Build Engine (Release)
        run: make -C ${{ env.BUILD_DIRECTORY }} config=release
        shell: cmd
